# Generated by Django 5.0.2 on 2024-04-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feature',
            new_name='features',
        ),
    ]
