# Generated by Django 5.0.2 on 2024-04-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback_delete_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='overall_experience',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='Overall Experience'),
        ),
    ]
